<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GiveawayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiveawayRepository extends EntityRepository
{
	public function filterQueryBuilder($filterData, $access)
	{
		$filterQuery = $this->createQueryBuilder('a');
		if(isset($filterData['form'])){
			foreach ($filterData['form'] as $filter => $data) {
				if (isset($data) && !empty($data)) {
					switch ($filter) {
						case 'name':
							$filterQuery = $filterQuery->Where('a.name LIKE :gname')
	                            ->setParameter('gname', "%" . $data . "%");
							break;
						case 'sortbyprice':
							$filterQuery = $filterQuery->addOrderBy('a.price', $data);
							break;
					}
				}
			}
		}
		
		if(!$access){
			$filterQuery = $filterQuery->andWhere('a.is_resticted = 0');
		}
		
		
		
		return  $filterQuery->getQuery()->getResult();
	}
}
